### ISSUE TITLE
Add meta engine support

### ISSUE THREAD

**Issue by afoucret** [elastic/app-search-php#27]
- [x] OpenAPI codegen update
   - [x] Support multiple method per path (https://github.com/elastic/openapi-codegen-php/pull/7)
   - [x] Tag new version
   - [X] Update codegen
- [X] Update OpenAPI spec & generate new endpoint
- [X] Test against App Search 7.6 (manual test only since a platinum license is required for this feature).
